### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by lvlind** [YetiForceCompany/YetiForcePDF#16]
Hi

Can't install your module using YetiForceCRM 5.1, getting error:
module does not contain default language (en_us)
can you help with it?
Best regards

**Comment by hico11** [comment]
Failed
Module does not contain default language (en_us).

Anyone have any idea how to sort this issue? It won't take.  The db settings all set to utf8 so not sure where the problems lies.  Everything else runs fast. 

Any suggestions appreciated.

**Comment by rafalpospiech** [comment]
Is this issue related to YetiForcePDF ?
YetiForcePDF is installed in YetiForceCRM by default
