### ISSUE TITLE
Typo in lib/layout/TableBox.php

### ISSUE THREAD

**Issue by gerripeach** [YetiForceCompany/YetiForcePDF#8]
Call to undefined method YetiForcePDF\Style\Style::getHorizotnalPaddingsWidth()

`getHorizotnalPaddingsWidth` must be called `getHorizontalPaddingsWidth`

**Comment by rafalpospiech** [comment]
It seems to be ok https://github.com/YetiForceCompany/YetiForcePDF/blob/developer/lib/Style/Style.php#L909

**Comment by rafalpospiech** [comment]
aaa you mean TableBox - right
fixed in 0.1.21
thanks
